SEPCO-SODOIT/Controllers/TransactionFilesController.cs
using SEPCO_SODOIT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Data;
using ClosedXML.Excel;
using System.Data.SqlClient;
using System.Configuration;
using SEPCO_SODOIT.Helpers;
using SEPCO;

namespace SEPCO_SODOIT.Controllers
{
    public class TransactionFilesController : Controller
    {
        int DefaultPageSize = 10;
        ApplicationDbContext DB = new ApplicationDbContext();
        // GET: TransactionFiles
        public ActionResult Index(int? page)
        {
            var pageNumber = page ?? 1; // if no page was specified in the querystring, default to the first page (1)
            var OnePageOfItems = DB._SYS_Transactions.Where(W => W.FileType.ToUpper() == "TRANSACTION FILE").OrderByDescending(O => O.ID);

            ViewBag.OnePageOfItems = OnePageOfItems.ToPagedList(pageNumber, DefaultPageSize); // will only contain 25 products max because of the pageSize
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportExcel(string TransactionFileList, HttpPostedFileBase upload)
        {
            var user = "Administrator";
            if (ModelState.IsValid)
            {

                if (upload != null && upload.ContentLength > 0)
                {
                    var FileType = TransactionFileList;
                    Stream stream = upload.InputStream;
                    DataTable breakDownDT = new DataTable();

                    switch (FileType)
                    {
                        case "AccountLevelChannelPSITF":
                            try
                            {
                                DataTable dt = HelperClass.ExcelToDataTable(stream, 0, 0, true, 1);
                                //Bring down data by Week Column
                                DataColumn dc = new DataColumn("ProductGroup", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("AP1", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Account", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Item", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Category", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Week", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Value", typeof(Decimal));
                                breakDownDT.Columns.Add(dc);
                                foreach (DataRow item in dt.Rows)
                                {
                                    foreach (DataColumn col in dt.Columns)
                                    {
                                        if (col.Ordinal >= 5)//Above 6th column are the weeks
                                        {
                                            DataRow row = breakDownDT.NewRow();
                                            row[0] = item[0].ToString();
                                            row[1] = item[1].ToString();
                                            row[2] = item[2].ToString();
                                            row[3] = item[3].ToString();
                                            row[4] = item[4].ToString();
                                            row[5] = col.ColumnName;//Week
                                            row[6] = item[col.Ordinal];//Week
                                            breakDownDT.Rows.Add(row);
                                        }
                                    }
                                }
                                if (HelperClass.CheckDataTable(breakDownDT))//valid
                                {
                                    //populate the transaction code
                                    var tCode = HelperClass.TransactionFileID(FileType);
                                    DataColumn Col = new DataColumn("TransactionID", System.Type.GetType("System.Int32"));
                                    Col.DefaultValue = tCode;
                                    breakDownDT.Columns.Add(Col);
                                    Col = new DataColumn("User", System.Type.GetType("System.String"));
                                    Col.DefaultValue = user;
                                    breakDownDT.Columns.Add(Col);

                                    //save in sql
                                    DataAccessLayer.SaveDataTF(breakDownDT, FileType, user);
                                }
                                else
                                {
                                    ModelState.AddModelError("File", "Invalid file");
                                }
                            }
                            catch (Exception e)
                            {

                            }
                            break;
                        case "AP1ForecastTransactionTF":
                            try
                            {
                                DataTable dt = HelperClass.ExcelToDataTable(stream, 0, 0, true, 1);
                                //Bring down data by Week Column
                                DataColumn dc = new DataColumn("ProductGroup", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Account", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Item", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Category", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Week", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Number", typeof(Decimal));
                                breakDownDT.Columns.Add(dc);
                                foreach (DataRow item in dt.Rows)
                                {
                                    foreach (DataColumn col in dt.Columns)
                                    {
                                        if (col.Ordinal >= 4)//5th or Above 5th column are the weeks
                                        {
                                            DataRow row = breakDownDT.NewRow();
                                            row[0] = item[1].ToString();
                                            row[1] = item[0].ToString();
                                            row[2] = item[2].ToString();
                                            row[3] = item[3].ToString();
                                            row[4] = col.ColumnName;//Week
                                            row[5] = item[col.Ordinal];//Value
                                            breakDownDT.Rows.Add(row);
                                        }
                                    }
                                }
                                if (HelperClass.CheckDataTable(breakDownDT))//valid
                                {
                                    //populate the transaction code
                                    var tCode = HelperClass.TransactionFileID(FileType);
                                    DataColumn Col = new DataColumn("TransactionID", System.Type.GetType("System.Int32"));
                                    Col.DefaultValue = tCode;
                                    breakDownDT.Columns.Add(Col);
                                    Col = new DataColumn("User", System.Type.GetType("System.String"));
                                    Col.DefaultValue = user;
                                    breakDownDT.Columns.Add(Col);

                                    //save in sql
                                    DataAccessLayer.SaveDataTF(breakDownDT, FileType, user);
                                }
                                else
                                {
                                    ModelState.AddModelError("File", "Invalid file");
                                }
                            }
                            catch (Exception ex)
                            {

                            }
                            break;
                        case "AP2PSITF":
                            try
                            {
                                DataTable dt = HelperClass.ExcelToDataTable(stream, 0, 0, true, 1);
                                //Bring down data by Week Column
                                DataColumn dc = new DataColumn("ProductGroup", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Item", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Category", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Week", typeof(String));
                                breakDownDT.Columns.Add(dc);
                                dc = new DataColumn("Value", typeof(Decimal));
                                breakDownDT.Columns.Add(dc);
                                foreach (DataRow item in dt.Rows)
                                {
                                    foreach (DataColumn col in dt.Columns)

SEPCO-SODOIT/Views/TransactionFiles/Index.cshtml
@using PagedList.Mvc;
@using PagedList;

@* file uploader *@
<h4>Transaction Files Upload</h4>

@using (Html.BeginForm("ImportExcel", "TransactionFiles", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-inline">
        <div class="form-group">
            <select id="TransactionFileList" class="form-control" name="TransactionFileList">
                <option value="0">-Select Master File to Upload-</option>
                <option value="AccountLevelChannelPSITF">Account Level Channel PSI Transaction File</option>
                <option value="AP1ForecastTransactionTF">AP1 Forecast Transaction File</option>
                <option value="AP2PSITF">AP2 PSI Transaction File</option>
                <option value="ExchangeRateTF">Exchange Rate Transaction File</option>
                <option value="FlooringTargetTF">Flooring Target Transaction File</option>
                <option value="FlooringSiteTF">Flooring Site Transaction File</option>
                <option value="GrossNetPriceTF">Gross & Net Price Transaction File</option>
                <option value="KPIAP1FAProductGroupTF">KPI AP1 FA Product Group Transaction File</option>
                <option value="KPIAP2FAProductGroupTF">KPI AP2 FA Product Group Transaction File</option>
                <option value="KPIAccountSellOutFATF">KPI Account Sell-Out FA Transaction File</option>
                <option value="SalesTargetTF">Sales Target Transaction File</option>
                <option value="SellInSellOutTargetTF">Sell-In & Sell-Out Target Transaction File</option>
                <option value="SellInBillingTF">Sell-In Billing Transaction File</option>
                <option value="SellInGITF">Sell-In GI Transaction File</option>
                <option value="SellOutInventoryTF">Sell-Out & Inventory Transaction File</option>
                <option value="SellOutTF">Sell-Out Transaction File</option>
                <option value="TIMTF">TIM Transaction File</option>
                <option value="WOSTransactionTF">WOS Transaction File</option>
            </select>
        </div>
        <div class="form-group">
            <input type="file" id="dataFile" name="upload" class="form-control"/>
        </div>

        <div class="form-group">
            <input type="submit" value="Upload" class="btn btn-default" />
        </div>
    </div>
}
<hr />
@* list of transactions *@
@*<table class="table table-responsive">*@
    @*<thead style="background:#0689d8;color:white;">
        <tr >
            <th>
                ID
            </th>
            <th>
                File
            </th>
            <th>
                Date Created
            </th>
            <th>
                Created By
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var items in ViewBag.OnePageOfItems)
        {
            <tr>
                <th>@items.ID</th>
                <th>@items.File</th>
                <th>@items.DateCreated</th>
                <th>@items.CreatedBy</th>
                <th><a href='@Url.Action("Delete", new { TransID = items.ID, FileType = items.File })' class="btn btn-danger">Delete</a> &nbsp;<a href='@Url.Action("Download", new { TransID = items.ID, FileType = items.FileType })' class="btn btn-info">Download</a></th>
            </tr>
        }
    </tbody>
</table>*@


<!-- output a paging control that lets the user navigation to the previous page, next page, etc -->
@*@Html.PagedListPager((IPagedList)ViewBag.OnePageOfItems, page => Url.Action("Index", new { page }))*@