SEPCO-SODOIT/Models/CarouselImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SEPCO_SODOIT.Models
{
    public class CarouselImage
    {
        [Key]
        public int ID { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
    }
}

SEPCO-SODOIT/Controllers/CarouselImageController.cs
using SEPCO_SODOIT.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SEPCO_SODOIT.Controllers
{
    public class CarouselImageController : Controller
    {
        ApplicationDbContext DB = new ApplicationDbContext();
        public ActionResult Index()
        {
            var list = DB._SYS_CAROUSELIMAGE.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CarouselImage img, HttpPostedFileBase file)
        {

            var allowedExtensions = new[] {  
            ".Jpg", ".png", ".jpg", "jpeg"  
                };
            //tbl.ID = Convert.ToInt32(fc["Id"]);

            img.Title = file.FileName;

            var fileName = Path.GetFileName(file.FileName);
            var ext = Path.GetExtension(file.FileName);
            if (allowedExtensions.Contains(ext))
            {
                string name = Path.GetFileNameWithoutExtension(fileName);
                string myfile = name + ext;
                //
                var path = Path.Combine(Server.MapPath("~/Images"), myfile);
                img.Path = path;
                DB._SYS_CAROUSELIMAGE.Add(img);
                DB.SaveChanges();
                file.SaveAs(path);
            }
            else
            {
                ViewBag.message = "Please choose only Image file";
            }

            return RedirectToAction("Index");


        }
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteGet(int id)
        {
            var listtodelete = DB._SYS_CAROUSELIMAGE.Find(id);
            return View(listtodelete);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {

            var listtodelete = DB._SYS_CAROUSELIMAGE.Find(id);
            DB._SYS_CAROUSELIMAGE.Remove(listtodelete);

            string fPath1 = Server.MapPath("~/Images/" + listtodelete.Title);
            System.IO.File.Delete(fPath1);
            DB.SaveChanges();
            return RedirectToAction("Index");
        }
      
    }
}

SEPCO-SODOIT/Views/CarouselImage/Create.cshtml
@model SEPCO_SODOIT.Models.CarouselImage

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2><b class="glyphicon glyphicon-plus"></b> Add New</h2>

@using (Html.BeginForm("Create", "CarouselImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()



    @ViewBag.message
    <div class="form-horizontal">
        <h4>CarouselImage</h4>
        <hr />

        <div class="col-md-2">&nbsp;</div>

        <div class="col-md-10">
            <div> <img id="user_img" height="100" width="90" style="border:solid" /></div>
            <br />
            <input type="file" name="file" id="file" onchange="show(this)" />
            <br />
        </div>
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    function show(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#user_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }
</script>  

SEPCO-SODOIT/Views/CarouselImage/Delete.cshtml
@model SEPCO_SODOIT.Models.CarouselImage

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarouselImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "CarouselImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SEPCO-SODOIT/Views/CarouselImage/Edit.cshtml
@model SEPCO_SODOIT.Models.CarouselImage

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Carousel Image Management</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (File.Exists(Server.MapPath("~/Images/"
 + Html.DisplayFor(modelItem => Model.ProductImage))))
{
    <img alt="" src="~/Images/@Html.DisplayFor(modelItem => Model.ProductImage)" />
    <form action="/CarouselImage/DeletePhoto" method="post" name="deletePhoto">
        @Html.AntiForgeryToken()

        <input type="text" name="photoFileName" value="@Html.DisplayFor(modelItem => Model.ProductImage)" />

        <input class="tiny button" type="submit" value="Delete" />
    </form>
}
else
{
    <form action="/CarouselImage/UploadPhoto" enctype="multipart/form-data" method="post">
        <label for="photo">Upload a Photo:</label>
        <input class="tiny button" id="photo" type="file" name="photo" />
        <input class="tiny button" type="submit" value="Upload" />
        <input type="hidden" name="cakesImage" value="@Html.DisplayFor(modelItem   => Model.ProductImage)" />
    </form>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SEPCO-SODOIT/Views/CarouselImage/Index.cshtml
@model IEnumerable<SEPCO_SODOIT.Models.CarouselImage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2><b class="glyphicon glyphicon-list"></b> CAROUSEL IMAGE MANAGEMENT</h2>

<p>
    <a href="@Url.Action("Create","CarouselImage")" class="btn btn-primary"><b class="glyphicon glyphicon-plus"></b> Add New</a>
</p>
<table class="table" id="myTable">
    <thead>
        <tr style="background:#0689d8;color:white;">

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>

                    <a href="@Url.Action("Delete", "CarouselImage", new { id = item.ID})" class="btn-sm btn-danger"><b class="glyphicon glyphicon-remove"></b></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>