SEPCO-SODOIT/Models/Dealer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SEPCO_SODOIT.Models
{
    public class Dealer
    {
        [Key]
        public int RecID { get; set; }
        [Required]
        public string DealerName { get; set; }
        public string Description { get; set; }
    }
}

SEPCO-SODOIT/Controllers/DealerController.cs
using SEPCO_SODOIT.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SEPCO_SODOIT.Controllers
{
    public class DealerController : Controller
    {
        ApplicationDbContext DB = new ApplicationDbContext();
        public ActionResult Index()
        {
            var dealerList = DB._SYS_DEALER.ToList();
            return View(dealerList);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Dealer dealer)
        {
            if (ModelState.IsValid)
            {
                DB._SYS_DEALER.Add(dealer);
                DB.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dealertoedit = DB._SYS_DEALER.Find(id);
            return View(dealertoedit);
        }
        [HttpPost]
        public ActionResult Edit(Dealer dealer)
        {
            if (ModelState.IsValid)
            {
                DB.Entry(dealer).State = EntityState.Modified;
                DB.SaveChanges();
            }
            return RedirectToAction("Index");

        }
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteGet(int id)
        {
            var dealertodelete = DB._SYS_DEALER.Find(id);
            return View(dealertodelete);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            var dealertodelete = DB._SYS_DEALER.Find(id);
            DB._SYS_DEALER.Remove(dealertodelete);
            DB.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SEPCO-SODOIT/Views/Dealer/Create.cshtml
@model SEPCO_SODOIT.Models.Dealer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><b class="glyphicon glyphicon-plus"></b> Add New</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dealer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DealerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DealerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DealerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SEPCO-SODOIT/Views/Dealer/Delete.cshtml
@model SEPCO_SODOIT.Models.Dealer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><b class="glyphicon glyphicon-remove"></b> Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dealer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Dealer Name</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DealerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SEPCO-SODOIT/Views/Dealer/Edit.cshtml
@model SEPCO_SODOIT.Models.Dealer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><b class="glyphicon glyphicon-edit"></b> Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dealer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecID)

        <div class="form-group">
            @Html.LabelFor(model => model.DealerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DealerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DealerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SEPCO-SODOIT/Views/Dealer/Index.cshtml
@model IEnumerable<SEPCO_SODOIT.Models.Dealer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><b class="glyphicon glyphicon-list"></b> DEALER MANAGEMENT</h2>

<p>
    <a href="@Url.Action("Create","Dealer")" class="btn btn-primary"><b class="glyphicon glyphicon-plus"></b> Add New</a>
</p>
<table class="table" id="myTable">
    <thead>
        <tr style="background:#0689d8;color:white;">
            <th>
                <label>Dealer Name</label>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DealerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Dealer", new { id= item.RecID})" class="btn-sm btn-success"><b class="glyphicon glyphicon-edit"></b></a>


                    <a href="@Url.Action("Delete", "Dealer", new { id = item.RecID })" class="btn-sm btn-danger"><b class="glyphicon glyphicon-remove"></b></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>