SEPCO-SODOIT/Controllers/MFDealerAccountMappingController.cs
using SEPCO_SODOIT.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SEPCO_SODOIT.Controllers
{
    public class MFDealerAccountMappingController : Controller
    {
        ApplicationDbContext DB = new ApplicationDbContext();
        public ActionResult Index()
        {
            var dam = DB._MF_DealerAndAccountStoreMapping.ToList();
            return View(dam);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Dealer = new SelectList(DB._SYS_DEALER.ToList(), "DealerName", "DealerName");

            ViewBag.GSCMAccount = new SelectList(DB._SYS_GSCMACCOUNT.ToList(), "AccountName", "AccountName");
            ViewBag.SiteGroup = new SelectList(DB._SYS_SITEGROUP.ToList(), "SiteGroupName", "SiteGroupName");
            return View();
        }
        [HttpPost]
        public ActionResult getSiteGroupID(string sitegroup)
        {
            var q = from p in DB._SYS_SITEGROUP
                    where p.SiteGroupName == sitegroup
                    select new
                    {
                        id = p.SiteGroupID
                    };
            return Json(q);
        }
        [HttpPost]
        public ActionResult getGSCMAccountID(string account)
        {
            var q = from p in DB._SYS_GSCMACCOUNT
                    where p.AccountName == account
                    select new
                    {
                        id = p.GSCMAccountID
                    };
            return Json(q);
        }
        [HttpPost]
        public ActionResult Create(MF_DealerAndAccountMapping dam)
        {
            DateTime dc = System.DateTime.Now;
            DateTime dm = System.DateTime.Now;

            dam.DateCreated = dc;
            dam.DateModified = dm;
            dam.CreatedBy = "Administrator";
            dam.ModifiedBy = "Administrator";
            dam.TransactionID = 1;


            DB._MF_DealerAndAccountMapping.Add(dam);
            DB.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            MF_DealerAndAccountMapping damtoedit = DB._MF_DealerAndAccountMapping.Find(id);
            ViewBag.Dealer = new SelectList(DB._SYS_DEALER.ToList(), "DealerName", "DealerName", damtoedit.Dealer);
            ViewBag.GSCMAccount = new SelectList(DB._SYS_GSCMACCOUNT.ToList(), "AccountName", "AccountName", damtoedit.GSCMAccount);
            ViewBag.SiteGroupName = new SelectList(DB._SYS_SITEGROUP.ToList(), "SiteGroupName", "SiteGroupName", damtoedit.SiteGroup);

            return View(damtoedit);

        }
        [HttpPost]
        public ActionResult Edit(MF_DealerAndAccountMapping dam)
        {
            DateTime dc = System.DateTime.Now;
            DateTime dm = System.DateTime.Now;

            dam.DateCreated = dc;
            dam.DateModified = dm;
            dam.CreatedBy = "Administrator";
            dam.ModifiedBy = "Administrator";
            dam.TransactionID = 1;
            DB.Entry(dam).State = EntityState.Modified;
            DB.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteGet(int id)
        {
            var damtodelete = DB._MF_DealerAndAccountMapping.Find(id);
            return View(damtodelete);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            var damtodelete = DB._MF_DealerAndAccountMapping.Find(id);
            DB._MF_DealerAndAccountMapping.Remove(damtodelete);
            DB.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SEPCO-SODOIT/Views/MFDealerAccountMapping/Create.cshtml
@model SEPCO_SODOIT.Models.MF_DealerAndAccountMapping

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dealer and Account Mapping</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SiteGroupID, htmlAttributes: new { @class = "control-label col-md-2" })
          
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteGroupID, new { htmlAttributes = new { @class = "form-control", @id = "SiteGroupID", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.SiteGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SiteGroup", ViewBag.SiteGroup as SelectList, "Select", new { @class = "form-control", @id = "SiteGroup" })
                @Html.ValidationMessageFor(model => model.SiteGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dealer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Dealer", ViewBag.Dealer as SelectList, new { @class = "form-control", @id = "ddlDealer" })
                @Html.ValidationMessageFor(model => model.Dealer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSCMAccountID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GSCMAccountID, new { htmlAttributes = new { @class = "form-control", @id = "gscmaccountID", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.GSCMAccountID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSCMAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GSCMAccount", ViewBag.GSCMAccount as SelectList, "Select", new { @class = "form-control", @id = "GSCMAccountID" })
                @*@Html.DropDownList("GSCMAccountID", ViewBag.GSCMAccount as SelectList, new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.GSCMAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AP1ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AP1ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AP1ID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">
    $(document).ready(function () {

        $('#GSCMAccountID').change(function () {
            //var url = "/MFDealerAccountMapping/getGSCMAccountID";
            $.ajax({
                url: '@Url.Action("getGSCMAccountID", "MFDealerAccountMapping")',
                type: "POST",
                data: { "account": $('#GSCMAccountID').val() },
                success: function (data) {
                    console.log(data);
                    if (data != null) {

                        $("#gscmaccountID").val(data[0].id);

                    }



                }
            });

        });

        $('#SiteGroup').change(function () {
            //var url = "/MFDealerAccountMapping/getGSCMAccountID";
            $.ajax({
                url: '@Url.Action("getSiteGroupID", "MFDealerAccountMapping")',
                type: "POST",
                data: { "sitegroup": $('#SiteGroup').val() },
                success: function (data) {
                    console.log(data);
                    if (data != null) {

                        $("#SiteGroupID").val(data[0].id);

                    }



                }
            });

        });
    });


</script>

SEPCO-SODOIT/Views/MFDealerAccountMapping/Delete.cshtml
@model SEPCO_SODOIT.Models.MF_DealerAndAccountMapping

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MFDealerAccountMapping</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SiteGroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteGroupID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SiteGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SiteGroup)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dealer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dealer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GSCMAccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GSCMAccountID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GSCMAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GSCMAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AP1ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AP1ID)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.IsUploaded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsUploaded)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.TransactionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SEPCO-SODOIT/Views/MFDealerAccountMapping/Edit.cshtml
@model SEPCO_SODOIT.Models.MF_DealerAndAccountMapping

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dealer and Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SiteGroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteGroupID, new { htmlAttributes = new { @class = "form-control", @id = "SiteGroupID", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.SiteGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SiteGroupName", null, "Select", new { @class = "form-control", @id = "SiteGroup" })
                @Html.ValidationMessageFor(model => model.SiteGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dealer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Dealer", null, "Select", new { @class = "form-control", @id = "Dealer" })
                @Html.ValidationMessageFor(model => model.Dealer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSCMAccountID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GSCMAccountID, new { htmlAttributes = new { @class = "form-control", @id = "gscmaccountID", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.GSCMAccountID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSCMAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GSCMAccount", null, "Select", new { @class = "form-control", @id = "GSCMAccount" })
                @Html.ValidationMessageFor(model => model.GSCMAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AP1ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AP1ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AP1ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $('#GSCMAccount').change(function () {
            //var url = "/MFDealerAccountMapping/getGSCMAccountID";
            $.ajax({
                url: '@Url.Action("getGSCMAccountID", "MFDealerAccountMapping")',
                type: "POST",
                data: { "account": $('#GSCMAccountID').val() },
                success: function (data) {
                    console.log(data);
                    if (data != null) {

                        $("#gscmaccountID").val(data[0].id);

                    }



                }
            });

        });

        $('#SiteGroup').change(function () {
            //var url = "/MFDealerAccountMapping/getGSCMAccountID";
            $.ajax({
                url: '@Url.Action("getSiteGroupID", "MFDealerAccountMapping")',
                type: "POST",
                data: { "sitegroup": $('#SiteGroup').val() },
                success: function (data) {
                    console.log(data);
                    if (data != null) {

                        $("#SiteGroupID").val(data[0].id);

                    }



                }
            });

        });
    });


</script>

SEPCO-SODOIT/Views/MFDealerAccountMapping/Index.cshtml
@model IEnumerable<SEPCO_SODOIT.Models.MF_DealerAndAccountMapping>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><b class="glyphicon glyphicon-list"></b> DEALER ACCOUNT MAPPING</h2>

<p>
    <a href="@Url.Action("Create","MFDealerAccountMapping")" class="btn btn-primary"><b class="glyphicon glyphicon-plus"></b> Add New</a>
</p>
<table class="table" id="myTable">
    <thead>
        <tr style="background:#0689d8;color:white;">
            <th>
                <label>Site Group ID</label>
            </th>
            <th>
                <label>Site Group</label>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dealer)
            </th>
            <th>
                <label>GSCM Account ID</label>
            </th>
            <th>
                <label>GSCM Account</label>
            </th>
            <th>
                <label>AP1 ID</label>
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SiteGroupID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SiteGroup)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dealer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GSCMAccountID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GSCMAccount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AP1ID)
                </td>

                <td>
                    <a href="@Url.Action("Edit", "MFDealerAccountMapping", new { id = item.RecID })" class="btn-sm btn-success"><b class="glyphicon glyphicon-edit"></b></a>
                    <a href="@Url.Action("Delete", "MFDealerAccountMapping", new { id = item.RecID })" class="btn-sm btn-danger"><b class="glyphicon glyphicon-remove"></b></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>